default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: vintage50_development

test:
  <<: *default
  database: vintage50_test

production:
  <<: *default
