# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 164dfa06f3cce64500ef8d9cfc7ec9bb86747d23f7bdbbd8114f4d94533488a19d8b7e724977331c748654ec57b47a8db2fa2a712795e3c00cdeb48af6bf7558

test:
  secret_key_base: 0ab259cbfe164c69a3ce168f8d072db7db389eb1cc4127eff4050c76e511c13ca49061e5f4ffe8b1d1295ef6b7921d88101befc1bd2a5d56ddf325967c2d2074

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
